# Use postgres/example user/password credentials
version: '3.1'

services:
#  mysql:
#    image: mysql:latest
#    ports:
#      - '3306:3306'
#    volumes:
#      - ./data:/var/lib/mysql
#    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_DATABASE=app
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./data2:/var/run/postgresql/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust